import { createElement } from "../../../utilities/createElement.js";
import { useDataStore } from "../../../stores/DataStore.js";
import { forecast } from "../../../lib/forecast.js";

import RocketLaunch from "../../icons/heroicons/RocketLaunch.js";

import styles from "./styles.js";

const { url } = useDataStore();

const PredictSection = () => {
  const section = createElement('section', 'id', 'section-one');
  const div3 = createElement('div', 'id', 'div3');
  const heading = createElement('h1');
  const paragraph = createElement('p');
  const div4 = createElement('div', 'id', 'div4');
  const button = createElement('a', 'id', 'button', 'type', 'button');
  const small = createElement('small');
  const small2 = createElement('small', 'id', 'small2');

  heading.textContent = 'Predict Today\'s Weather';
  paragraph.innerHTML = 'GPT Weather is a Node.js&reg; console app that generates random weather forecasts each time the program runs. The random pieces of data were generated by ChatGPT 3.5.';
  button.innerHTML = `Run GPT Weather ${RocketLaunch}`;
  small.innerHTML = 'Runs a script <span>modified</span> for the browser. Open the browser console to view and reload to run the original.';
  small2.innerHTML = `Want to learn more? Visit the <a href="${url['github-repo']}">GitHub repo</a> for details.`;

  document.querySelector('main').appendChild(section);
  document.getElementById('section-one').appendChild(div3);
  document.getElementById('div3').appendChild(heading);
  document.getElementById('div3').appendChild(paragraph);
  document.getElementById('section-one').appendChild(div4);
  document.getElementById('div4').appendChild(button);
  document.getElementById('div4').appendChild(small);
  document.getElementById('div4').appendChild(small2);

  button.onclick = forecast;

  styles();
};

export default PredictSection;
