import { createElement, formatForecast } from "./utilities/index.js";
import { useCopyToClipboard } from "./wrappers/index.js";
import { applyStyles } from "./styles/applyStyles.js";
import { useDataStore } from "./stores/DataStore.js";

import {
  RocketLaunch,
  CommandLine,
  ClipboardDocument
} from "./components/icons/index.js";

import { NavBar, Footer } from "./components/index.js";

const { url } = useDataStore();
const copyToClipboard = useCopyToClipboard();

function initialForecast() {
  formatForecast()

  let innerText = document.getElementById('output2').innerText;
  while (innerText.includes('clear') || innerText.includes('showers')) {
    formatForecast()
    innerText = document.getElementById('output2').innerText;
  }
}

function copyForecast() {
  const toCopy = document.getElementById('output1').innerText;
  const toCopy2 = document.getElementById('output2').innerText;

  copyToClipboard(toCopy + toCopy2);
}

function formatDocument() {

  NavBar();

  const container = createElement('div', 'id', 'container');
  const backdrop = createElement('div', 'id', 'backdrop');
  const main = createElement('main');

  const section = createElement('section', 'id', 'section-one');
  const div3 = createElement('div', 'id', 'div3');
  const heading = createElement('h1');
  const paragraph = createElement('p');
  const div4 = createElement('div', 'id', 'div4');
  const button = createElement('a', 'id', 'button', 'type', 'button');
  const small = createElement('small');
  const small2 = createElement('small');

  const section2 = createElement('section', 'id', 'section-two');
  const div5 = createElement('div', 'id', 'div5');
  const console1 = createElement('div', 'id', 'console1');
  const span = createElement('span');
  const console2 = createElement('div', 'id', 'console2');
  const pre = createElement('pre', 'id', 'pre');
  const code = createElement('code');
  const span2 = createElement('span', 'id', 'output1');
  const span3 = createElement('span', 'id', 'output2');
  const div6 = createElement('div', 'id', 'div6');
  const button2 = createElement('a', 'id', 'button2', 'type', 'button');
  const paragraph2 = createElement('p');

  heading.textContent = 'Predict Today\'s Weather';
  paragraph.innerHTML = 'GPT Weather is a Node.js&reg; console app that generates random weather forecasts each time the program runs. The random pieces of data were generated by ChatGPT 3.5.';
  button.innerHTML = `Run GPT Weather ${RocketLaunch}`;
  small.innerHTML = 'Runs a script <span>modified</span> for the browser. Open the browser console to view and reload to run the original.';
  small2.innerHTML = `Want to learn more? Visit the <a href="${url['github-repo']}">GitHub repo</a> for details.`;

  span.innerHTML = `${CommandLine} Console`;
  button2.innerHTML = `${ClipboardDocument} Copy to clipboard`;
  paragraph2.innerHTML = `Learn how the color changes by checking out the <a href="${url['github-repo']}/blob/master/src/main.js">source code</a>.`;

  document.getElementById('app').appendChild(container);
  document.getElementById('container').appendChild(backdrop);
  document.getElementById('container').appendChild(main);

  document.querySelector('main').appendChild(section);
  document.getElementById('section-one').appendChild(div3);
  document.getElementById('div3').appendChild(heading);
  document.getElementById('div3').appendChild(paragraph);
  document.getElementById('section-one').appendChild(div4);
  document.getElementById('div4').appendChild(button);
  document.getElementById('div4').appendChild(small);
  document.getElementById('div4').appendChild(small2);

  document.querySelector('main').appendChild(section2);
  document.getElementById('section-two').appendChild(div5);
  document.getElementById('div5').appendChild(console1);
  document.getElementById('console1').appendChild(span);
  document.getElementById('div5').appendChild(console2);
  document.getElementById('console2').appendChild(pre);
  document.getElementById('pre').appendChild(code);
  document.querySelector('code').appendChild(span2);
  document.querySelector('code').appendChild(span3);
  document.getElementById('console2').appendChild(div6);
  document.getElementById('div6').appendChild(button2);
  document.getElementById('section-two').appendChild(paragraph2);

  Footer();

  button.onclick = formatForecast;
  button2.onclick = copyForecast;

  initialForecast()
  applyStyles()
}

formatDocument()
